apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: helloweb-service
  labels:
    app: helloweb-service
spec:
  type: ClusterIP
  ports:
  - port: 38080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: hello
    tier: web